#! /bin/sh
if ["$1" = "close"]; then
 ECHO Admin privileges required
 sudo -v
 ECHO Admin acquired...
 sudo launchctl disable system/com.qustodio.engine
 sudo launchctl disable system/com.qustodio.update
 ECHO launchtl disabled...
 sudo launchctl stop system/com.qustodio.engine
 sudo launchctl stop system/com.qustodio.update
 ECHO launchctl stopped...
 ECHO Done. A system restart would be recommended though just in case...
elif ["$1" = "open"]; then
 ECHO Admin privileges required
 sudo -v
 ECHO Admin acquired...
 sudo launchctl enable system/com.qustodio.engine
 sudo launchctl enable system/com.qustodio.update
 ECHO launchctl enabled...
 sudo launchctl start system/com.qustodio.engine
 sudo launchctl start system/com.qustodio.update
 ECHO launchctl started...
 ECHO Done...
fi
